version: '3'
services:
  qdrant:
    container_name: qdrantdb
    image: qdrant/qdrant
    ports:
      - '6333:6333'
      - '6334:6334'
  # pgvector:
  #   image: ankane/pgvector
  #   container_name: pgvector-for-study
  #   ports:
  #     - '${PORT_PGVECTOR}:5432'
  #   volumes:
  #     - ./script:/docker-entrypoint-initdb.d
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   tty: true
  #   restart: always
  #   user: root
